version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: my_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "21212:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
